---
- name: Render the elasticsearch systemd template
  template:
    src: "elastic_search.systemd.j2"
    dest: "/etc/systemd/system/elasticsearch_monitoring.service"
    owner: root
    group: root
    mode: "0644"
  register: "elasticsearch_systemd_config"
  notify:
    - "es_exporter systemd restart"
  tags:
    - es

- name: "Enable and start the elasticsearch_monitoring systemd service"
  systemd:
    name: elasticsearch_monitoring
    state: started
    enabled: True
    daemon_reload: yes
  tags:
    - es
